// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AnalyticsVisualization {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("Account_List")]
	public partial class Account_List {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("Account_ListController")]
	public partial class Account_ListController {
		
		private global::MonoMac.AppKit.NSTableView __mt__accountList;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Connect("_accountList")]
		private global::MonoMac.AppKit.NSTableView _accountList {
			get {
				this.__mt__accountList = ((global::MonoMac.AppKit.NSTableView)(this.GetNativeField("_accountList")));
				return this.__mt__accountList;
			}
			set {
				this.__mt__accountList = value;
				this.SetNativeField("_accountList", value);
			}
		}
	}
}
