// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AnalyticsVisualization {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("VisualizationWindow")]
	public partial class VisualizationWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("VisualizationWindowController")]
	public partial class VisualizationWindowController {
		
		private global::MonoMac.AppKit.NSTableView __mt__visualizationTable;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Connect("_visualizationTable")]
		private global::MonoMac.AppKit.NSTableView _visualizationTable {
			get {
				this.__mt__visualizationTable = ((global::MonoMac.AppKit.NSTableView)(this.GetNativeField("_visualizationTable")));
				return this.__mt__visualizationTable;
			}
			set {
				this.__mt__visualizationTable = value;
				this.SetNativeField("_visualizationTable", value);
			}
		}
	}
}
